"""Initial Migration

Revision ID: 726cbfb93b5a
Revises: daa8c1e25fe3
Create Date: 2019-09-12 05:37:31.334032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726cbfb93b5a'
down_revision = 'daa8c1e25fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
